development:
  username: cheesewiz
  password: showmethecheddar
  adapter: postgresql
  database: smoked-delights-dev
  host: localhost
  port: 5432
  pool: 50
  timeout: 5000

test:
  username: cheesewiz
  password: showmethecheddar
  adapter: postgresql
  database: smoked-delights-test
  host: localhost
  port: 5432
  pool: 50
  timeout: 5000

production:
  username: cheesewiz
  password: showmethecheddar
  adapter: postgresql
  database: smoked-delights-production
  pool: 50
  timeout: 5000
